branch-defaults:
  master:
    environment: digitalleaf-env
    group_suffix: null
global:
  application_name: DigitalLeaf
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: eb-cli
  repository: null
  sc: git
